edith/urls.py
from django.urls import path
from . import views

app_name = 'edith'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

hackathon/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('', include('edith.urls')),
    path('admin/', admin.site.urls),
]

edith/models.py
from django.db import models


# Create your models here.
class City(models.Model):
    city_text = models.CharField(max_length=20)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.city_text


class Camera(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    camera_text = models.CharField(max_length=20)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.camera_text


class CameraHistory(models.Model):
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    timestamp = models.DateTimeField('updated at')
    status = models.FloatField()

    def __str__(self):
        return f'{self.camera} {self.timestamp} {self.status}'


class Agent(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name_text = models.CharField(max_length=25)
    email = models.EmailField(blank=True)
    position = models.CharField(max_length=10)

    def __str__(self):
        return self.name

edith/views.py
from django.shortcuts import render
from django.views import generic
from .models import City
from .models import Camera


# Create your views here.
def index(request):
    return render(request, 'edith/index.html')


def about(request):
    return render(request, 'edith/about.html')


class DetailView(generic.DetailView):
    model = City

    def get_queryset(self):
        return Camera.objects.all()

templates/edith/about.html
{% extends "edith/base.html" %}

{% load static %}

{% block title %}About{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Welcome to the Future of Smart City</h1>
        <p class="lead">Have you ever wished you could protect citizens without having to worry about when it will
            happen or how many people you can protect?</p>
        <hr class="my-4">
        <p class="lead">We're using the latest developments in machine learning to offload the repetitive parts of
            real-time monitoring.</p>
    </div>
    <div class="jumbotron">
        <h3>We want to automate away the tedious parts of supervision, so you can focus on what you need to do most:
            smart decisions.
        </h3>
        <hr class="my-4">
        <p>Everyone knows that programming is central to the future as every industry becomes transformed by software.
            We imagine a world where machine learning allows cameras to become assistants — E.D.I.T.H is
            the first step to achieving that vision.
        </p>
    </div>
    <img src="{% static "images/kite_team.jpg" %}" class="img-fluid" alt="E.D.I.T.H Team">
    <blockquote class="blockquote text-center">
        <p class="mb-0">E.D.I.T.H’s engineering team of University of Greenwich (Viet Nam) possesses the technical chops
            to pull off
            artificial intelligence in the cloud for the most critical of audiences: developers.</p>
        <footer class="blockquote-footer">The Unsittables</footer>
    </blockquote>
{% endblock %}

templates/edith/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
    <link rel="shortcut icon" href="{% static "images/favicon_v2.png" %}"/>
    <title>{% block title %}E.D.I.T.H - Official Home Page{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        <img src="{% static "images/favicon_v2.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
        E.D.I.T.H
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "edith:about" %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">FAQ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Support</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="container ">
    {% block content %}{% endblock %}
    <hr/>
    <footer>
        <p>&copy; 2019 - The Unsittables</p>
    </footer>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="{% static "js/bootstrap.bundle.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

templates/edith/index.html
{% extends "edith/base.html" %}

{% load static %}

{% block content %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static "images/background_2.jpg" %}" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide label</h5>
                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static "images/background_3.jpg" %}" alt="Second slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="text-center">
        <img src="{% static "images/gmplot.png" %}" class="img-fluid rounded">
    </div>
    <div class="jumbotron">
        <h1 class="display-4">Everything you need in one place</h1>
        <p class="lead">Outlook mobile delivers a connected experience across email, search and calendar and deeply
            integrates with Office apps, files and teams to power your productivity and collaboration. </p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
    <div class="jumbotron">
        <h1 class="display-4">Protect and manage with ease</h1>
        <p class="lead">Protect your data without compromising productivity with security you can trust. Outlook mobile
            has enterprise-grade app and device management capabilities built-in to safeguard your information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
    <div class="jumbotron">
        <h1 class="display-4">Help center</h1>
        <p class="lead">Set up, optimize your experience or access frequently asked questions about Outlook mobile.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
{% endblock %}